<?php
function headerColumns($key = ''){
    $columns = [
        'crons' => [
            ['SL', 'SL'],
            ['process', 'process', 'text-center'],
            ['output', 'output'],
            ['at', 'at', 'text-center'],
        ],
        'modules' => [
            ['SL', 'SL', 'text-center'],
            ['serial', 'serial', 'text-center'],
            ['name', 'name', 'text-center'],
            ['route', 'route', 'text-center'],
            ['icon', 'icon', 'text-center'],
            ['menu', 'menu', 'text-center'],
            ['description', 'description'],
            ['actions', 'actions', 'text-center'],
        ],
        'menu' => [
            ['SL', 'SL', 'text-center'],
            ['module', 'module', 'text-center'],
            ['serial', 'serial', 'text-center'],
            ['name', 'name', 'text-center'],
            ['route', 'route', 'text-center'],
            ['icon', 'icon', 'text-center'],
            ['submenu', 'submenu', 'text-center'],
            ['description', 'description', 'text-center'],
            ['actions', 'actions', 'text-center'],
        ],
        'submenu' => [
            ['SL', 'SL', 'text-center'],
            ['module', 'module', 'text-center'],
            ['menu', 'menu', 'text-center'],
            ['serial', 'serial', 'text-center'],
            ['name', 'name', 'text-center'],
            ['route', 'route', 'text-center'],
            ['icon', 'icon', 'text-center'],
            ['description', 'description', 'text-center'],
            ['actions', 'actions', 'text-center'],
        ],
        'permissions' => [
            ['SL', 'SL', 'text-center'],
            ['module', 'module', 'text-center'],
            ['name', 'name', 'text-center'],
            ['guard_name', 'guard_name', 'text-center'],
            ['actions', 'actions', 'text-center'],
        ],
        'roles' => [
            ['SL', 'SL', 'text-center'],
            ['name', 'name', 'text-center'],
            ['guard_name', 'guard_name', 'text-center'],
            ['actions', 'actions', 'text-center'],
        ],
        'users' => [
            ['SL', 'SL', 'text-center'],
            ['image', 'image', 'text-center'],
            ['name', 'name', 'text-center'],
            ['email', 'email', 'text-center'],
            ['username', 'username', 'text-center'],
            ['roles', 'roles', 'text-center'],
            ['actions', 'actions', 'text-center'],
        ],
        'languages' => [
            ['SL', 'SL', 'text-center'],
            ['code', 'code', 'text-center'],
            ['name', 'name'],
            ['direction', 'direction', 'text-center'],
            ['flag', 'flag', 'text-center'],
            ['actions', 'actions', 'text-center'],
        ],
        'countries' => [
            ['SL', 'SL', 'text-center'],
            ['code', 'code', 'text-center'],
            ['name', 'name', 'text-center'],
            ['nationality', 'nationality', 'text-center'],
            ['actions', 'actions', 'text-center'],
        ],
        'cities' => [
            ['SL', 'SL', 'text-center'],
            ['country', 'country', 'text-center'],
            ['code', 'code', 'text-center'],
            ['name', 'name', 'text-center'],
            ['description', 'description', 'text-center'],
            ['actions', 'actions', 'text-center'],
        ],
        'entry-types' => [
            ['SL', 'SL', 'text-center'],
            ['name', 'name', 'text-center'],
            ['sign', 'sign', 'text-center'],
            ['color', 'color', 'text-center'],
            ['positive', 'positive', 'text-center'],
            ['icon', 'icon', 'text-center'],
            ['description', 'description', 'text-center'],
            ['actions', 'actions', 'text-center'],
        ],
    ];

    return isset($columns[$key]) ? $columns[$key] : array(['SL', 'SL', 'text-center']);
}