<?php
function headerColumns($key = ''){
    $columns = [
        'crons' => [
            ['SL', 'SL'],
            ['process', 'process', 'text-center'],
            ['output', 'output'],
            ['at', 'at', 'text-center'],
        ],
        'publishment-types' => [
            ['SL', 'SL', 'text-center'],
            ['name', 'name', 'text-center'],
            ['description', 'description', 'text-center'],
            ['actions', 'actions', 'text-center'],
        ],
        'publishments' => [
            ['SL', 'SL'],
            ['type', 'type', 'text-center'],
            ['title', 'title', 'text-center'],
            ['from', 'from', 'text-center'],
            ['to', 'to', 'text-center'],
            ['actions', 'actions', 'text-center'],
        ],
        'religions' => [
            ['SL', 'SL', 'text-center'],
            ['name', 'name', 'text-center'],
            ['description', 'description', 'text-center'],
            ['actions', 'actions', 'text-center'],
        ],
        'modules' => [
            ['SL', 'SL', 'text-center'],
            ['serial', 'serial', 'text-center'],
            ['name', 'name', 'text-center'],
            ['route', 'route', 'text-center'],
            ['icon', 'icon', 'text-center'],
            ['menu', 'menu', 'text-center'],
            ['description', 'description'],
            ['actions', 'actions', 'text-center'],
        ],
        'menu' => [
            ['SL', 'SL', 'text-center'],
            ['module', 'module', 'text-center'],
            ['serial', 'serial', 'text-center'],
            ['name', 'name', 'text-center'],
            ['route', 'route', 'text-center'],
            ['icon', 'icon', 'text-center'],
            ['submenu', 'submenu', 'text-center'],
            ['description', 'description', 'text-center'],
            ['actions', 'actions', 'text-center'],
        ],
        'submenu' => [
            ['SL', 'SL', 'text-center'],
            ['module', 'module', 'text-center'],
            ['menu', 'menu', 'text-center'],
            ['serial', 'serial', 'text-center'],
            ['name', 'name', 'text-center'],
            ['route', 'route', 'text-center'],
            ['icon', 'icon', 'text-center'],
            ['description', 'description', 'text-center'],
            ['actions', 'actions', 'text-center'],
        ],
        'permissions' => [
            ['SL', 'SL', 'text-center'],
            ['module', 'module', 'text-center'],
            ['name', 'name', 'text-center'],
            ['guard_name', 'guard_name', 'text-center'],
            ['actions', 'actions', 'text-center'],
        ],
        'roles' => [
            ['SL', 'SL', 'text-center'],
            ['name', 'name', 'text-center'],
            ['guard_name', 'guard_name', 'text-center'],
            ['actions', 'actions', 'text-center'],
        ],
        'holiday-types' => [
            ['SL', 'SL', 'text-center'],
            ['name', 'name', 'text-center'],
            ['description', 'description', 'text-center'],
            ['actions', 'actions', 'text-center'],
        ],
        'holidays' => [
            ['SL', 'SL', 'text-center'],
            ['holiday_type', 'holiday_type', 'text-center'],
            ['name', 'name', 'text-center'],
            ['date', 'date', 'text-center'],
            ['description', 'description', 'text-center'],
            ['actions', 'actions', 'text-center'],
        ],
        'users' => [
            ['SL', 'SL', 'text-center'],
            ['image', 'image', 'text-center'],
            ['name', 'name', 'text-center'],
            ['email', 'email', 'text-center'],
            ['username', 'username', 'text-center'],
            ['roles', 'roles', 'text-center'],
            ['actions', 'actions', 'text-center'],
        ],
        'languages' => [
            ['SL', 'SL', 'text-center'],
            ['code', 'code', 'text-center'],
            ['name', 'name'],
            ['direction', 'direction', 'text-center'],
            ['flag', 'flag', 'text-center'],
            ['actions', 'actions', 'text-center'],
        ],
        'countries' => [
            ['SL', 'SL', 'text-center'],
            ['code', 'code', 'text-center'],
            ['name', 'name', 'text-center'],
            ['nationality', 'nationality', 'text-center'],
            ['actions', 'actions', 'text-center'],
        ],
        'cities' => [
            ['SL', 'SL', 'text-center'],
            ['country', 'country', 'text-center'],
            ['code', 'code', 'text-center'],
            ['name', 'name', 'text-center'],
            ['description', 'description', 'text-center'],
            ['actions', 'actions', 'text-center'],
        ],
        'suppliers' => [
            ['SL', 'SL', 'text-center'],
            ['city', 'city', 'text-center'],
            ['name', 'name', 'text-center'],
            ['phone', 'phone', 'text-center'],
            ['email', 'email', 'text-center'],
            ['address', 'address', 'text-center'],
            ['description', 'description', 'text-center'],
            ['image', 'image', 'text-center'],
            ['actions', 'actions', 'text-center'],
        ],
        'customers' => [
            ['SL', 'SL', 'text-center'],
            ['city', 'city', 'text-center'],
            ['name', 'name', 'text-center'],
            ['phone', 'phone', 'text-center'],
            ['email', 'email', 'text-center'],
            ['address', 'address', 'text-center'],
            ['description', 'description', 'text-center'],
            ['image', 'image', 'text-center'],
            ['actions', 'actions', 'text-center'],
        ],
        'product-categories' => [
            ['SL', 'SL', 'text-center'],
            ['name', 'name', 'text-center'],
            ['description', 'description', 'text-center'],
            ['actions', 'actions', 'text-center'],
        ],
        'brands' => [
            ['SL', 'SL', 'text-center'],
            ['name', 'name', 'text-center'],
            ['description', 'description', 'text-center'],
            ['image', 'image', 'text-center'],
            ['actions', 'actions', 'text-center'],
        ],
        'products' => [
            ['SL', 'SL', 'text-center'],
            ['category', 'category', 'text-center'],
            ['brand', 'brand', 'text-center'],
            ['sku', 'sku', 'text-center'],
            ['name', 'name', 'text-center'],
            ['price', 'price', 'text-center'],
            ['tags', 'tags', 'text-center'],
            ['details', 'details', 'text-center'],
            ['actions', 'actions', 'text-center'],
        ],
        'employees' => [
            ['SL', 'SL', 'text-center'],
            ['image', 'image', 'text-center'],
            ['first_name', 'first_name', 'text-center'],
            ['middle_name', 'middle_name', 'text-center'],
            ['last_name', 'last_name', 'text-center'],
            ['phone', 'phone', 'text-center'],
            ['email', 'email', 'text-center'],
            ['address', 'address', 'text-center'],
            ['identity', 'identity', 'text-center'],
            ['passport', 'passport', 'text-center'],
            ['license', 'license', 'text-center'],
            ['type', 'type', 'text-center'],
            ['description', 'description', 'text-center'],
            ['actions', 'actions', 'text-center'],
        ],

        'ledgers' => [
            ['SL', 'SL', 'text-center'],
            ['type', 'type', 'text-center'],
            ['code', 'code', 'text-center'],
            ['name', 'name', 'text-center'],
            ['description', 'description', 'text-center'],
            ['creator', 'creator', 'text-center'],
            ['editor', 'editor', 'text-center'],
            ['actions', 'actions', 'text-center'],
        ],
        'entries' => [
            ['SL', 'SL', 'text-center'],
            ['code', 'code', 'text-center'],
            ['reference', 'reference', 'text-center'],
            ['datetime', 'datetime', 'text-center'],
            ['income', 'income', 'text-center'],
            ['expense', 'expense', 'text-center'],
            ['notes', 'notes', 'text-center'],
            ['creator', 'creator', 'text-center'],
            ['editor', 'editor', 'text-center'],
            ['actions', 'actions', 'text-center'],
        ],

        'exchanges' => [
            ['SL', 'SL', 'text-center'],
            ['code', 'code', 'text-center'],
            ['supplier', 'supplier', 'text-center'],
            ['product', 'product', 'text-center'],
            ['asking_price', 'asking_price', 'text-center'],
            ['exchange_price', 'exchange_price', 'text-center'],
            ['status', 'status', 'text-center'],
            ['requested_at', 'requested_at', 'text-center'],
            ['exchanged_at', 'exchanged_at', 'text-center'],
            ['creator', 'creator', 'text-center'],
            ['editor', 'editor', 'text-center'],
            ['actions', 'actions', 'text-center'],
        ],
        
        'procurements' => [
            ['SL', 'SL', 'text-center'],
            ['code', 'code', 'text-center'],
            ['supplier', 'supplier', 'text-center'],
            ['product', 'product', 'text-center'],
            ['asking_price', 'asking_price', 'text-center'],
            ['procurement_price', 'procurement_price', 'text-center'],
            ['status', 'status', 'text-center'],
            ['requested_at', 'requested_at', 'text-center'],
            ['procured_at', 'procured_at', 'text-center'],
            ['creator', 'creator', 'text-center'],
            ['editor', 'editor', 'text-center'],
            ['actions', 'actions', 'text-center'],
        ],

        'sales' => [
            ['SL', 'SL', 'text-center'],
            ['code', 'code', 'text-center'],
            ['customer', 'customer', 'text-center'],
            ['product', 'product', 'text-center'],
            ['price', 'price', 'text-center'],
            ['datetime', 'datetime', 'text-center'],
            ['creator', 'creator', 'text-center'],
            ['actions', 'actions', 'text-center'],
        ],

        'purchases' => [
            ['SL', 'SL', 'text-center'],
            ['code', 'code', 'text-center'],
            ['customer', 'customer', 'text-center'],
            ['product', 'product', 'text-center'],
            ['asking_price', 'asking_price', 'text-center'],
            ['purchase_price', 'purchase_price', 'text-center'],
            ['status', 'status', 'text-center'],
            ['taken_at', 'taken_at', 'text-center'],
            ['purchased_at', 'purchased_at', 'text-center'],
            ['creator', 'creator', 'text-center'],
            ['editor', 'editor', 'text-center'],
            ['actions', 'actions', 'text-center'],
        ],
        
        'auctions' => [
            ['SL', 'SL', 'text-center'],
            ['code', 'code', 'text-center'],
            ['name', 'name', 'text-center'],
            ['product', 'product', 'text-center'],
            ['quantity', 'quantity', 'text-center'],
            ['base_price', 'base_price', 'text-center'],
            ['duration', 'duration', 'text-center'],
            ['bids', 'bids', 'text-center'],
            ['status', 'status', 'text-center'],
            ['winner', 'winner', 'text-center'],
            ['creator', 'creator', 'text-center'],
            ['editor', 'editor', 'text-center'],
            ['actions', 'actions', 'text-center'],
        ],

        'supplier-payments' => [
            ['SL', 'SL', 'text-center'],
            ['supplier', 'supplier', 'text-center'],
            ['type', 'type', 'text-center'],
            ['datetime', 'datetime', 'text-center'],
            ['amount', 'amount', 'text-center'],
            ['description', 'description', 'text-center'],
            ['creator', 'creator', 'text-center'],
            ['editor', 'editor', 'text-center'],
            ['actions', 'actions', 'text-center'],
        ],
        'customer-payments' => [
            ['SL', 'SL', 'text-center'],
            ['customer', 'customer', 'text-center'],
            ['type', 'type', 'text-center'],
            ['datetime', 'datetime', 'text-center'],
            ['amount', 'amount', 'text-center'],
            ['description', 'description', 'text-center'],
            ['creator', 'creator', 'text-center'],
            ['editor', 'editor', 'text-center'],
            ['actions', 'actions', 'text-center'],
        ],
        'customer-collections' => [
            ['SL', 'SL', 'text-center'],
            ['customer', 'customer', 'text-center'],
            ['type', 'type', 'text-center'],
            ['datetime', 'datetime', 'text-center'],
            ['amount', 'amount', 'text-center'],
            ['description', 'description', 'text-center'],
            ['creator', 'creator', 'text-center'],
            ['editor', 'editor', 'text-center'],
            ['actions', 'actions', 'text-center'],
        ],
    ];

    return isset($columns[$key]) ? $columns[$key] : array(['SL', 'SL', 'text-center']);
}